In [13]:
from pathlib import Path
import os
data_dir = str(Path.home()) + r'/coursematerial/GIS/ISPRS'
filepath = os.path.join(data_dir, r'Vaihingen3DTraining.las')
print(filepath)

/home/jovyan/coursematerial/GIS/ISPRS/Vaihingen3DTraining.las


In [14]:
import laspy
import numpy as np
file= laspy.read('/home/jovyan/coursematerial/GIS/ISPRS/Vaihingen3DTraining.las')
xyz = np.stack((file.x, file.y, file.z), axis=1)
np.set_printoptions(precision=2,suppress=True)
print(xyz)
print(xyz.shape)

[[ 496848.91 5419403.58     265.46]
 [ 496848.92 5419403.97     265.43]
 [ 496848.93 5419404.35     265.4 ]
 ...
 [ 497066.43 5419331.1      266.89]
 [ 497066.43 5419331.36     266.87]
 [ 497066.44 5419331.63     266.88]]
(753876, 3)


In [15]:
from sklearn.neighbors import KDTree
kd_tree_3d =KDTree(xyz)
distances3d,indices3d=kd_tree_3d.query(xyz, k=40)
print(distances3d)
print(indices3d)
print(distances3d.shape)
print(indices3d.shape)

[[0.   0.12 0.37 ... 3.05 3.18 3.22]
 [0.   0.14 0.28 ... 2.95 3.   3.04]
 [0.   0.17 0.25 ... 2.9  2.9  2.95]
 ...
 [0.   0.   0.15 ... 0.88 0.92 0.92]
 [0.   0.   0.15 ... 0.89 0.97 0.97]
 [0.   0.   0.15 ... 0.97 0.97 0.99]]
[[     0 131981     10 ... 132064 132066 132026]
 [     1 131982 131981 ... 132064 132026 132066]
 [     2 131983 131982 ... 132062 132064 132066]
 ...
 [422915 753873 648126 ... 648124 648128 276754]
 [753874 422916 753673 ... 277290 753677 422450]
 [422917 753875 753672 ... 648125 276751 753676]]
(753876, 40)
(753876, 40)


In [16]:
d15, i15 =kd_tree_3d.query(xyz[15:16,:],k=40)
print(d15)
print(i15)
print(d15.shape)
print(i15.shape)
print(xyz[i15].shape)
print(xyz[i15])

[[0.   0.67 0.88 0.97 1.01 1.1  1.18 1.34 1.38 1.44 1.45 1.45 1.45 1.46
  1.47 1.48 1.53 1.63 1.63 1.69 1.7  1.74 1.75 1.75 1.76 1.81 1.82 1.84
  1.86 1.88 1.89 1.9  2.01 2.06 2.08 2.09 2.1  2.11 2.14 2.19]]
[[    15 131987      4      5 131988 132011      6 132026 131989 132024
       7 132028     40 131984 132009     19     12      3 132030 132070
  132072 131983 132068 131990      8     38 132074     20 132032 132008
  132066      2 132076 131982     53 132064      9 131991 132033     37]]
(1, 40)
(1, 40)
(1, 40, 3)
[[[ 496850.22 5419405.73     265.21]
  [ 496850.13 5419405.07     265.22]
  [ 496849.34 5419405.72     265.3 ]
  [ 496849.33 5419405.36     265.34]
  [ 496850.11 5419404.74     265.36]
  [ 496850.41 5419404.67     265.41]
  [ 496849.32 5419404.99     265.37]
  [ 496851.53 5419405.44     265.28]
  [ 496850.08 5419404.37     265.39]
  [ 496851.58 5419406.19     265.25]
  [ 496849.31 5419404.62     265.38]
  [ 496851.51 5419405.09     265.37]
  [ 496850.61 5419407.13     26

In [17]:
print(indices3d[20])
print(distances3d[20])
print(xyz[indices3d[20]])

[    20     38     19     21     37     40     36     34     53     56
     97     59     15 132076 132024     95 132074      4 132082     93
 132072     91      5 132026 131987 132070     89      6     63 132113
 132115 132028    165 132111    161 131988 132068 132110 132011 131984]
[0.   0.35 0.36 0.37 0.47 0.55 0.75 1.11 1.2  1.34 1.72 1.8  1.84 1.9
 1.9  1.91 2.07 2.08 2.13 2.15 2.31 2.41 2.41 2.47 2.5  2.57 2.69 2.76
 2.76 2.76 2.77 2.77 2.78 2.79 2.79 2.84 2.86 2.89 2.91 2.95]
[[ 496850.28 5419407.57     265.2 ]
 [ 496850.62 5419407.5      265.2 ]
 [ 496850.27 5419407.21     265.2 ]
 [ 496850.29 5419407.94     265.15]
 [ 496850.63 5419407.88     265.17]
 [ 496850.61 5419407.13     265.19]
 [ 496850.64 5419408.23     265.16]
 [ 496850.65 5419408.61     265.1 ]
 [ 496851.47 5419407.39     265.16]
 [ 496851.5  5419408.13     265.14]
 [ 496851.85 5419408.26     265.12]
 [ 496851.52 5419408.87     265.07]
 [ 496850.22 5419405.73     265.21]
 [ 496851.97 5419406.71     265.18]
 [ 49685

In [18]:
slice_i15 =xyz[i15]
print(np.reshape(slice_i15,(60,2)).shape)
print(np.squeeze(slice_i15).shape)
print(slice_i15.shape)
print(slice_i15[0,:].shape)

(60, 2)
(40, 3)
(1, 40, 3)
(40, 3)


In [19]:
z=np.random.randint(0,9,(1,3,1,5))
print(z)
print(np.squeeze(z,axis=0).shape)
print(np.squeeze(z).shape)

[[[[0 2 4 8 3]]

  [[1 4 5 7 8]]

  [[8 3 7 3 6]]]]
(3, 1, 5)
(3, 5)


In [20]:
covi15=np.cov(np.squeeze(xyz[i15],axis=0),rowvar=False)
print(covi15)
w_value,v_vector=np.linalg.eig(covi15)
print(w_value)
print(v_vector)

[[ 1.07  0.39  0.01]
 [ 0.39  1.38 -0.12]
 [ 0.01 -0.12  0.02]]
[1.65 0.81 0.01]
[[ 0.56  0.83 -0.04]
 [ 0.83 -0.55  0.1 ]
 [-0.06  0.09  0.99]]


In [33]:
from sklearn.neighbors import KDTree
import numpy as np
import time
from datetime import timedelta
start_time=time.process_time()
w1=np.zeros((np.shape(xyz)[0],3))
v1=np.zeros((np.shape(xyz)[0],3,3))
print(v1)
print(w1)

for i in range(xyz.shape[0]):
    dst,ind =kd_tree_3d.query(xyz[i:i+1,:],k=40)
    c = np.cov(np.squeeze(xyz[ind], axis=0), rowvar=False)
    w1[i],v1[i,:]=np.linalg.eig(c)
    
end_time = time.process_time()
print(timedelta(seconds=end_time - start_time))


    




[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0:01:35.943665


In [ ]:
start_time = time.process_time()
distances3d, indices3d = kd_tree_3d.query(xyz, k=20)
w2 = np.zeros((np.shape(xyz)[0], 3))
v2 = np.zeros((np.shape(xyz)[0], 3, 3))
for i in range(xyz.shape[0]):
     c = np.cov(xyz[indices3d[i]], rowvar=False)
    w2[i], v2[i,:] = np.linalg.eig(c)
end_time = time.process_time()
print(timedelta(seconds=end_time - start_time))